spring.application.name=startstudents

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Configurações do banco PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/projects
spring.datasource.username=starstudent_bd
spring.datasource.password=345216
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

